# frozen_string_literal: true

module Engine
  module Game
    module G18HN
      module Entities
        HANAU_HEX = 'J15'

        # 11.1: obligated track routes in printed order, each stop lists the hexes that count for it
        OBLIGATIONS = {
          'WEG' => [%w[J9], %w[J5], %w[J3 G2]],
          'LTB' => [%w[J3 G2], %w[H7], %w[G10]],
          'MNB' => [%w[O10], %w[N11], %w[L11], %w[J11 J13]],
          'HLB' => [%w[J3 G2], %w[K4], %w[K8], %w[N5 O8]],
          'VB' => [%w[F17], %w[G12]],
          'MWB' => [%w[F13], %w[G12], %w[J11 J13]],
          'FWN' => [%w[D17], %w[C18], %w[A18]],
          'FHB' => [%w[G20], %w[E18]],
          'WLB' => [%w[D15], %w[C14], %w[B15]],
        }.freeze

        # 11.1: SB's obligation is to build all three Odenwald hexes
        BUILT_OBLIGATIONS = { 'SB' => %w[M12 N13 O12] }.freeze

        COMPANIES = [
          {
            name: 'Homburger Bahn',
            sym: 'HB',
            value: 20,
            revenue: 5,
            desc: 'lay free special tile in Bad Homburg with the first 5-Train.',
            abilities: [
              { type: 'blocks_hexes', owner_type: 'player', hexes: ['I10'] },
              {
                type: 'tile_lay',
                owner_type: 'player',
                hexes: %w[I10],
                tiles: %w[939],
                discount: 40,
                reachable: false,
                when: 'any',
                count: 1,
              },
],
            color: nil,
            meta: { start_packet: true },
          },
          {
            name: 'Seidler & Siebrecht',
            sym: 'SS',
            value: 30,
            revenue: 10,
            desc: 'Close this private for reducing the cost of a tile lay to 0M.',
            abilities: [
                        {
                          type: 'tile_lay',
                          owner_type: 'player',
                          hexes: 'any',
                          tiles: 'yellow',
                          discount: 60,
                          reachable: false,
                          when: 'player',
                          count: 1,
                        },
],
            meta: { start_packet: true },
            color: nil,
          },
          {
            name: 'Baugesellschaft Rheinbrücken',
            sym: 'BR',
            value: 40,
            revenue: 10,
            count: 2,
            desc: 'can build two free bridges, close after the second bridge.',
            meta: { start_packet: true },
            color: nil,
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'player_or_company',
                hexes: %w[K4 J5 K8 J9 K10 L9 N9 N11],
                tiles: %w[9],
                when: 'player',
                count: 2,
              },
            ],
          },
          {
            name: 'Frankfurter Lokalbahn AG',
            sym: 'FL',
            value: 50,
            revenue: 0,
            desc: 'Director may lay one tile in Frankfurt at start of each OR.'\
                  ' Owns the concession rights of city passage of Frankfurt',
            meta: { start_packet: true },
            abilities: [
              {
                type: 'tile_lay',
                owner_type: 'player',
                hexes: %w[J11 J13],
                tiles: %w[921 922 923 924],
                reachable: false,
                when: 'any',
                count: 4,
                connect: false,
              },
              { type: 'acquire_company', company: 'FC' },
],
            color: nil,
          },
          {
            name: 'Baugesellschaft Edertalsperre',
            sym: 'BE',
            value: 60,
            revenue: 15,
            desc: 'Exchange for share of WLB and lay free tile in Bad Wildungen.',
            meta: { start_packet: true },
            abilities: [
              { type: 'close', on_phase: 'never' },
              {
                type: 'exchange',
                corporations: ['WLB'],
                owner_type: 'player',
                when: 'any',
                from: 'reserved',
              },
              {
                type: 'tile_lay',
                owner_type: 'player',
                hexes: 'D15',
                discount: 60,
                tiles: %w[3 4 58],
                when: 'exchange',
                count: 1,
              },
              { type: 'acquire_company', company: 'WC' },

            ],
            color: nil,
          },
          {
            name: 'Frankfurt-Hanauer Bahn',
            sym: 'FB',
            value: 70,
            revenue: 15,
            desc: 'Exchange for share of FHB and lay free token in Hanau.',
            meta: { start_packet: true },
            abilities: [
              {
                type: 'token',
                owner_type: 'player',
                hexes: [HANAU_HEX],
                when: 'any',
                count: 1,
              },
              { type: 'acquire_company', company: 'HKC' },
              {
                type: 'exchange',
                corporations: ['FHB'],
                owner_type: 'player',
                when: 'any',
                from: 'reserved',
              },
            ],
            color: nil,
          },
          {
            name: 'Taunusbahn',
            sym: 'TB',
            value: 80,
            revenue: 15,
            desc: 'Exchange for share of WEG and lay free yellow tile in one Taunus Space.',
            meta: { start_packet: true },
            abilities: [
              { type: 'close', on_phase: 'never' },
              {
                type: 'tile_lay',
                owner_type: 'player',
                hexes: %w[I4 I6 I8],
                tiles: %w[3 4 58 7 8 9],
                when: 'exchange',
                discount: 40,
                count: 1,
              },
              { type: 'acquire_company', company: 'NC' },
              {
                type: 'exchange',
                corporations: ['WEG'],
                owner_type: 'player',
                when: 'any',
                from: 'reserved',
              },
            ],
            color: nil,
          },
          {
            name: 'Odenwaldbahn',
            sym: 'OB',
            value: 90,
            revenue: 15,
            desc: 'Exchange for share of SB and lay free yellow tile in one Odenwald Space.',
            meta: { start_packet: true },
            abilities: [
              { type: 'close', on_phase: 'never' },
              {
                type: 'tile_lay',
                owner_type: 'player',
                hexes: %w[M12 N13 O12],
                tiles: %w[3 4 58 7 8 9],
                discount: 40,
                when: 'exchange',
                count: 1,
              },
              { type: 'acquire_company', company: 'HDC' },
              {
                type: 'exchange',
                corporations: ['SB'],
                owner_type: 'player',
                when: 'any',
                from: 'reserved',
              },
            ],
            color: nil,
          },
          {
            name: 'Waldeck Concession',
            sym: 'WC',
            value: 0,
            revenue: 0,
            desc: 'Concession rights for operations in Waldeck. Sell rights for 40M to Owner',
            abilities: [{ type: 'no_buy' }],
            color: nil,
            meta: { start_packet: false },
          },
          {
            name: 'Hessen-Kassel Concession',
            sym: 'HKC',
            value: 0,
            revenue: 0,
            desc: 'Concession rights for operations in Hessen-Kassel. Sell rights for 40M to Owner',
            color: nil,
            abilities: [{ type: 'no_buy' }],
            meta: { start_packet: false },
          },
          {
            name: 'Nassau Concession',
            sym: 'NC',
            value: 0,
            revenue: 0,
            desc: 'Concession rights for operations in Nassau. Sell rights for 40M to Owner',
            color: nil,
            abilities: [{ type: 'no_buy' }],
            meta: { start_packet: false },
          },
          {
            name: 'Hessen-Darmstadt Concession',
            sym: 'HDC',
            value: 0,
            revenue: 0,
            desc: 'Concession rights for operations in Hessen-Darmstadt. Sell rights for 40M to Owner',
            color: nil,
            abilities: [{ type: 'no_buy' }],
            meta: { start_packet: false },
          },
          {
            name: 'Frankfurt Concession',
            sym: 'FC',
            value: 0,
            revenue: 0,
            desc: 'Concession rights for city passage of Frankfurt. Sell rights for 40M to Owner',
            color: nil,
            abilities: [{ type: 'no_buy' }],
            meta: { start_packet: false },
          },
        ].freeze

        CORPORATIONS = [
          {
            float_percent: 50,
            sym: 'SB',
            name: 'Starkenburg Bahn',
            logo: '18_hn/SB',
            simple_logo: '18_hn/SB.alt',
            tokens: [0, 40, 100],
            ipo_shares: [20, 10, 10, 10, 10, 10, 10, 10],
            reserved_shares: [10],
            coordinates: 'L11',
            color: :gray,
          },
          {
            float_percent: 50,
            sym: 'MNB',
            name: 'Main-Neckar-Bahn',
            logo: '18_hn/MNB',
            simple_logo: '18_hn/mnb.alt',
            tokens: [0, 40, 100],
            coordinates: 'N11',
            color: :blue,
          },
          {
            float_percent: 50,
            sym: 'HLB',
            name: 'Hessische Landesbahn',
            logo: '18_hn/HLB',
            simple_logo: '18_hn/hlb.alt',
            tokens: [0, 40, 100],
            coordinates: 'K8',
            color: :white,
            text_color: 'black',
          },
          {
            float_percent: 50,
            sym: 'VB',
            name: 'Vogelsberg-Bahn',
            logo: '18_hn/VB',
            simple_logo: '18_hn/vb.alt',
            tokens: [0, 40, 100],
            coordinates: 'F17',
            color: :brown,
          },
          {
            float_percent: 50,
            sym: 'WEG',
            name: 'Wiesbadener Eisenbahngesellschaft',
            logo: '18_hn/WEG',
            simple_logo: '18_hn/weg.alt',
            tokens: [0, 40, 100],
            ipo_shares: [20, 10, 10, 10, 10, 10, 10, 10],
            reserved_shares: [10],
            coordinates: 'J9',
            color: :'#ADD8E6',
            text_color: :green,
          },
          {
            float_percent: 50,
            sym: 'LTB',
            name: 'Lahntal-Bahn',
            logo: '18_hn/LTB',
            simple_logo: '18_hn/ltb.alt',
            tokens: [0, 40, 100],
            coordinates: 'H7',
            color: :orange,
            text_color: 'black',
          },
          {
            float_percent: 50,
            sym: 'FHB',
            name: 'Fulda-Hanauer Bahn',
            logo: '18_hn/FHB',
            simple_logo: '18_hn/fhb.alt',
            tokens: [0, 40],
            coordinates: 'G20',
            ipo_shares: [20, 10, 10, 10, 10, 10, 10, 10],
            reserved_shares: [10],
            city: 0,
            color: :purple,
          },
          {
            float_percent: 50,
            sym: 'MWB',
            name: 'Main-Weser-Bahn',
            logo: '18_hn/MWB',
            simple_logo: '18_hn/mwb.alt',
            tokens: [0, 40, 100],
            coordinates: 'F13',
            color: :red,
          },
          {
            float_percent: 50,
            sym: 'WLB',
            name: 'Waldecksche Landesbahn',
            logo: '18_hn/WLB',
            simple_logo: '18_hn/wlb.alt',
            tokens: [0, 40, 100],
            coordinates: 'C14',
            ipo_shares: [20, 10, 10, 10, 10, 10, 10, 10],
            reserved_shares: [10],
            city: 0,
            color: :yellow,
            text_color: :black,
          },
          {
            float_percent: 50,
            sym: 'FWN',
            name: 'Friedrich-Wilhelm-Nordbahn',
            logo: '18_hn/FWN',
            simple_logo: '18_hn/fwn.alt',
            tokens: [0, 40, 100],
            coordinates: 'C18',
            color: :lightgreen,
          },
        ].freeze
      end
    end
  end
end
